// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OcrApi.Data;

#nullable disable

namespace OcrApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250821103156_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OcrApi.Models.CustomsReceipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Organization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CustomsReceipts");
                });

            modelBuilder.Entity("OcrApi.Models.DocumentData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomsDeclarationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomsPaymentDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomsPaymentNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DocumentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ImportDuty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsCustomsReceipt")
                        .HasColumnType("bit");

                    b.Property<string>("OcrResultId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("OtherFees")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TotalAmountText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Vat")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("DocumentData");
                });

            modelBuilder.Entity("OcrApi.Models.ExpenseItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FinancialDocumentDataId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FinancialDocumentDataId");

                    b.ToTable("ExpenseItems");
                });

            modelBuilder.Entity("OcrApi.Models.FinancialDocumentData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomsDeclarationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomsPaymentDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomsPaymentNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DocumentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ImportDuty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PersonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TotalAmountText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Vat")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("FinancialDocuments");
                });

            modelBuilder.Entity("OcrApi.Models.ItemsInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomsReceiptId")
                        .HasColumnType("int");

                    b.Property<decimal>("ImportDuty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Other")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Vat")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomsReceiptId")
                        .IsUnique();

                    b.ToTable("ItemsInfos");
                });

            modelBuilder.Entity("OcrApi.Models.OcrResult", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("float");

                    b.Property<string>("ExtractedText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FinancialDataId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FinancialDataId");

                    b.ToTable("OcrResults");
                });

            modelBuilder.Entity("OcrApi.Models.ReferenceInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomsReceiptId")
                        .HasColumnType("int");

                    b.Property<string>("DeclarantName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeclarationNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hawb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImportExportDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentRef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomsReceiptId")
                        .IsUnique();

                    b.ToTable("ReferenceInfos");
                });

            modelBuilder.Entity("OcrApi.Models.SignInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomsReceiptId")
                        .HasColumnType("int");

                    b.Property<string>("Officer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Receiver")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomsReceiptId")
                        .IsUnique();

                    b.ToTable("SignInfos");
                });

            modelBuilder.Entity("OcrApi.Models.TotalInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AmountText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomsReceiptId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomsReceiptId")
                        .IsUnique();

                    b.ToTable("TotalInfos");
                });

            modelBuilder.Entity("OcrApi.Models.ExpenseItem", b =>
                {
                    b.HasOne("OcrApi.Models.FinancialDocumentData", null)
                        .WithMany()
                        .HasForeignKey("FinancialDocumentDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OcrApi.Models.ItemsInfo", b =>
                {
                    b.HasOne("OcrApi.Models.CustomsReceipt", null)
                        .WithOne("Items")
                        .HasForeignKey("OcrApi.Models.ItemsInfo", "CustomsReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OcrApi.Models.OcrResult", b =>
                {
                    b.HasOne("OcrApi.Models.FinancialDocumentData", "FinancialData")
                        .WithMany()
                        .HasForeignKey("FinancialDataId");

                    b.Navigation("FinancialData");
                });

            modelBuilder.Entity("OcrApi.Models.ReferenceInfo", b =>
                {
                    b.HasOne("OcrApi.Models.CustomsReceipt", null)
                        .WithOne("Reference")
                        .HasForeignKey("OcrApi.Models.ReferenceInfo", "CustomsReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OcrApi.Models.SignInfo", b =>
                {
                    b.HasOne("OcrApi.Models.CustomsReceipt", null)
                        .WithOne("Sign")
                        .HasForeignKey("OcrApi.Models.SignInfo", "CustomsReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OcrApi.Models.TotalInfo", b =>
                {
                    b.HasOne("OcrApi.Models.CustomsReceipt", null)
                        .WithOne("Total")
                        .HasForeignKey("OcrApi.Models.TotalInfo", "CustomsReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OcrApi.Models.CustomsReceipt", b =>
                {
                    b.Navigation("Items")
                        .IsRequired();

                    b.Navigation("Reference")
                        .IsRequired();

                    b.Navigation("Sign")
                        .IsRequired();

                    b.Navigation("Total")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
